name: Fetch and Update Posts
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # 매 시간마다 실행
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 전체 히스토리를 가져옵니다
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Fetch posts and update JSON
        run: node .github/scripts/fetch_posts.js
      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Pull latest changes
        run: |
          git pull origin main
          git merge --strategy-option theirs
      - name: Commit posts.json if changed
        uses: EndBug/add-and-commit@v9
        with:
          add: 'posts.json'
          message: 'Update posts.json'
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
